"""Artifact loading helpers for the TwinAgent AI API.

The API is intentionally artifact-driven. It reads the outputs generated by:

    python scripts/run_full_pipeline.py

This keeps the serving layer lightweight and makes Docker/API behavior match the
tested backend pipeline.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd


def project_root_from_api_file() -> Path:
    """Return project root from this file location."""
    return Path(__file__).resolve().parents[3]


def artifact_metadata(path: Path, *, project_root: Path) -> dict[str, Any]:
    """Return metadata for one artifact path."""
    exists = path.exists()
    metadata: dict[str, Any] = {
        "path": str(path.relative_to(project_root) if path.is_relative_to(project_root) else path),
        "exists": exists,
    }
    if exists:
        stat = path.stat()
        metadata.update(
            {
                "size_bytes": int(stat.st_size),
                "modified_epoch": float(stat.st_mtime),
            }
        )
    return metadata


def read_json(path: Path, *, default: Any = None) -> Any:
    """Read JSON file if it exists."""
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def read_markdown(path: Path, *, default: str = "") -> str:
    """Read Markdown/text file if it exists."""
    if not path.exists():
        return default
    return path.read_text(encoding="utf-8")


def read_latest_sensor_row(path: Path) -> dict[str, Any]:
    """Return latest row from a processed sensor CSV."""
    if not path.exists():
        return {}
    dataframe = pd.read_csv(path)
    if dataframe.empty:
        return {}
    return dataframe.sort_values("timestamp").iloc[-1].to_dict()


def read_csv_preview(path: Path, *, limit: int = 20) -> list[dict[str, Any]]:
    """Return a small CSV preview."""
    if not path.exists():
        return []
    dataframe = pd.read_csv(path)
    return dataframe.head(limit).to_dict(orient="records")


def artifact_paths(project_root: Path) -> dict[str, Path]:
    """Return all API-known artifact paths."""
    return {
        "local_sensor_data": project_root / "data" / "generated" / "sensor_data.csv",
        "local_processed_data": project_root / "data" / "processed" / "sensor_data_with_anomalies.csv",
        "local_predictions": project_root / "data" / "processed" / "sensor_data_with_fault_predictions.csv",
        "local_prediction_audit": project_root / "data" / "processed" / "fault_prediction_audit.csv",
        "local_incidents": project_root / "data" / "incidents" / "incidents.json",
        "local_incidents_with_ml": project_root / "data" / "incidents" / "incidents_with_ml.json",
        "local_incidents_reconciled": project_root / "data" / "incidents" / "incidents_reconciled.json",
        "local_work_orders": project_root / "data" / "reports" / "local_work_orders.json",
        "pipeline_summary": project_root / "data" / "reports" / "pipeline_run_summary.json",
        "ml_metrics": project_root / "models" / "fault_classifier_metrics.json",
        "ml_error_analysis": project_root / "models" / "fault_classifier_error_analysis.json",
        "ml_feature_importance": project_root / "models" / "fault_classifier_feature_importance.csv",
        "ml_model_card": project_root / "models" / "fault_classifier_model_card.md",
        "fleet_processed_data": project_root / "data" / "fleet" / "processed" / "fleet_sensor_data_with_anomalies.csv",
        "fleet_incidents": project_root / "data" / "fleet" / "incidents" / "fleet_incidents.json",
        "fleet_summary": project_root / "data" / "fleet" / "reports" / "fleet_summary.json",
        "fleet_triage": project_root / "data" / "fleet" / "reports" / "fleet_triage.json",
        "fleet_global_analysis": project_root / "data" / "fleet" / "reports" / "global_fleet_analysis.json",
        "fleet_work_orders": project_root / "data" / "fleet" / "reports" / "fleet_work_orders.json",
    }


def artifact_status(project_root: Path) -> dict[str, Any]:
    """Return status for all known artifacts."""
    paths = artifact_paths(project_root)
    artifacts = {
        name: artifact_metadata(path, project_root=project_root)
        for name, path in paths.items()
    }

    required_for_serving = [
        "local_processed_data",
        "local_incidents_reconciled",
        "local_work_orders",
        "pipeline_summary",
        "ml_metrics",
        "fleet_summary",
        "fleet_triage",
        "fleet_work_orders",
    ]
    missing_required = [
        name
        for name in required_for_serving
        if not artifacts[name]["exists"]
    ]

    return {
        "status": "ready" if not missing_required else "missing_artifacts",
        "missing_required": missing_required,
        "artifacts": artifacts,
    }


def compact_system_summary(project_root: Path) -> dict[str, Any]:
    """Return compact operational summary from pipeline outputs."""
    paths = artifact_paths(project_root)
    pipeline = read_json(paths["pipeline_summary"], default={}) or {}
    ml_metrics = read_json(paths["ml_metrics"], default={}) or {}
    fleet_summary = read_json(paths["fleet_summary"], default={}) or {}
    local_reconciled = read_json(paths["local_incidents_reconciled"], default=[]) or []
    local_work_orders = read_json(paths["local_work_orders"], default={}) or {}
    fleet_work_orders = read_json(paths["fleet_work_orders"], default={}) or {}

    review_count = sum(
        1 for incident in local_reconciled
        if isinstance(incident, dict) and incident.get("requires_review") is True
    )

    return {
        "pipeline_status": pipeline.get("status", "unknown"),
        "local_incidents": len(read_json(paths["local_incidents"], default=[]) or []),
        "reconciled_incidents": len(local_reconciled),
        "review_required_incidents": review_count,
        "fleet_machines": int((fleet_summary.get("fleet") or {}).get("machine_count", 0)) if isinstance(fleet_summary, dict) else 0,
        "fleet_incidents": int((fleet_summary.get("fleet") or {}).get("incident_rows", 0)) if isinstance(fleet_summary, dict) else 0,
        "ml_window_count": int(ml_metrics.get("window_count", 0)) if isinstance(ml_metrics, dict) else 0,
        "ml_class_count": int(ml_metrics.get("class_count", 0)) if isinstance(ml_metrics, dict) else 0,
        "ml_weighted_f1": ml_metrics.get("weighted_f1") if isinstance(ml_metrics, dict) else None,
        "local_work_orders": int(local_work_orders.get("total_work_orders", 0)) if isinstance(local_work_orders, dict) else 0,
        "fleet_work_orders": int(fleet_work_orders.get("total_work_orders", 0)) if isinstance(fleet_work_orders, dict) else 0,
    }
